name: Roughnote
description: A Social Media App.

version: 1.3.0+4

environment: 
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  image_picker: ^0.8.4+4
  firebase_storage: ^10.1.0
  firebase_auth: ^1.2.0
  google_sign_in: ^5.0.4
  uuid: ^3.0.4
  image: ^3.0.2
  cupertino_icons: ^1.0.4
  path_provider: ^2.0.2
  firebase_messaging: ^11.2.10
  flutter_svg: ^0.22.0
  cached_network_image: ^3.0.0
  timeago: ^3.0.2
  material_design_icons_flutter: ^5.0.5955-rc.1
  firebase_core: ^1.2.0
  font_awesome_flutter: ^9.0.0
  flutter_svg_provider: ^0.1.9
  fluttertoast: ^8.0.7
  photo_view: ^0.12.0
  container_tab_indicator: ^0.3.0
  nb_utils: ^4.4.1
  google_fonts: ^2.3.1
  provider: ^6.0.2
  story_view: ^0.13.1
  flutter_staggered_grid_view: ^0.4.0
  share: ^2.0.4
  url_launcher: ^6.0.10
  flutter_linkify: ^5.0.2
  simple_animations: ^3.1.1
  ionicons: ^0.1.2
  link_preview_generator: ^1.1.0
  another_flushbar: ^1.10.20
  fluttericon: ^2.0.0
  paginate_firestore: ^1.0.3
  flutter_reaction_button: ^2.0.0+1
  file_picker: ^4.1.6
  visibility_detector: ^0.3.3
  filesize: ^2.0.1
  easy_pdf_viewer: ^1.0.1
  adaptive_theme: ^2.3.0
  video_player: ^2.2.5
  flick_video_player: ^0.4.0-dev.4
  string_validator: ^0.3.0
  google_mobile_ads: ^2.2.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  badges: ^2.0.2
  iconly: ^1.0.1
  video_compress: ^3.1.0
  webview_flutter: ^2.0.12
  flutter_mobx: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  geolocator: ^8.1.1
  geolocator_web: ^2.1.4
  geocoding: ^2.0.2
  giphy_get: ^2.0.4
  in_app_purchase: ^3.0.5
  scoped_model: ^2.0.0-nullsafety.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1


 
 

 

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true
  uses-material-design: true
 

  assets:
    - assets/icon.png
    - assets/images/
    


    

