name: simpleworld
description: A new Flutter project.

version: 1.3.1+5

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  adaptive_theme: ^3.2.1
  another_flushbar: ^1.10.20
  badges: ^3.1.1
  cached_network_image: ^3.0.0
  cloud_firestore: ^4.7.0
  connectivity_plus_web: ^1.2.5
  container_tab_indicator: ^0.3.0
  crypto: ^3.0.1
  cupertino_icons: ^1.0.4
  easy_pdf_viewer: ^1.0.1
  equatable: ^2.0.3
  file_picker: ^5.2.10
  filesize: ^2.0.1
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_messaging: ^14.6.0
  firebase_storage: ^11.2.0
  flick_video_player: ^0.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_linkify: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_reaction_button: ^2.0.0+1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.7
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.0.2
  geolocator: ^9.0.2
  geolocator_web: ^2.1.4
  giphy_get: ^3.4.0
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  google_sign_in: ^6.1.0
  iconly: ^1.0.1
  image: ^4.0.17
  image_picker: ^0.8.4+4
  in_app_purchase: ^3.0.5
  intl: ^0.18.0
  ionicons: ^0.2.2
  json_annotation: ^4.4.0
  link_preview_generator: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  nb_utils: ^5.0.8
  path_provider: ^2.0.2
  photo_view: ^0.14.0
  provider: ^6.0.2
  scoped_model: ^2.0.0-nullsafety.0
  share: ^2.0.4
  sign_in_with_apple: ^4.3.0
  simple_animations: ^5.0.0+3
  story_view: ^0.14.0
  string_validator: ^1.0.0
  timeago: ^3.0.2
  url_launcher: ^6.0.10
  uuid: ^3.0.4
  video_compress: ^3.1.0
  video_player: ^2.2.5
  visibility_detector: ^0.3.3
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.png"
  android: true
  ios: true
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/images/
